#!/bin/bash

echo "🚀 Deploying Bliq Chat Application to Render..."
echo ""
echo "📋 Pre-deployment checklist:"
echo "✅ WAR file built successfully"
echo "✅ Database configuration updated"
echo "✅ Dockerfile optimized"
echo "✅ Render configuration created"
echo ""

echo "🌐 Deployment Options:"
echo ""
echo "Option 1: Deploy to Render (Recommended - Free tier available)"
echo "==========================================================="
echo "1. Go to https://render.com and create an account"
echo "2. Click 'New' -> 'Web Service'"
echo "3. Connect your GitHub repository"
echo "4. Choose 'Docker' as the environment"
echo "5. Set the following environment variables:"
echo "   - DATABASE_URL: jdbc:mysql://bhnnqi71g2wqrpwustfv-mysql.services.clever-cloud.com:3306/bhnnqi71g2wqrpwustfv"
echo "   - DATABASE_USER: uqrllnmuff3ztkgj"
echo "   - DATABASE_PASSWORD: 2ZFEDD7YO5EnzHRYN5QJ"
echo "6. Deploy!"
echo ""

echo "Option 2: Deploy to Heroku"
echo "=========================="
echo "1. Install Heroku CLI: curl https://cli-assets.heroku.com/install.sh | sh"
echo "2. heroku login"
echo "3. heroku create your-app-name"
echo "4. heroku config:set DATABASE_URL=jdbc:mysql://bhnnqi71g2wqrpwustfv-mysql.services.clever-cloud.com:3306/bhnnqi71g2wqrpwustfv"
echo "5. heroku config:set DATABASE_USER=uqrllnmuff3ztkgj"
echo "6. heroku config:set DATABASE_PASSWORD=2ZFEDD7YO5EnzHRYN5QJ"
echo "7. git push heroku main"
echo ""

echo "Option 3: Deploy to Fly.io"
echo "=========================="
echo "1. Install flyctl: curl -L https://fly.io/install.sh | sh"
echo "2. fly auth login"
echo "3. fly launch"
echo "4. fly secrets set DATABASE_URL=jdbc:mysql://bhnnqi71g2wqrpwustfv-mysql.services.clever-cloud.com:3306/bhnnqi71g2wqrpwustfv"
echo "5. fly secrets set DATABASE_USER=uqrllnmuff3ztkgj"
echo "6. fly secrets set DATABASE_PASSWORD=2ZFEDD7YO5EnzHRYN5QJ"
echo "7. fly deploy"
echo ""

echo "🎯 Quick Start with Render (Easiest Option):"
echo "============================================"
echo "1. Push this code to GitHub if you haven't already"
echo "2. Go to https://render.com/dashboard"
echo "3. Click 'New' -> 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Render will automatically detect the Dockerfile"
echo "6. Set environment variables as listed above"
echo "7. Click 'Create Web Service'"
echo ""

echo "📊 Database Information:"
echo "Host: bhnnqi71g2wqrpwustfv-mysql.services.clever-cloud.com"
echo "Port: 3306"
echo "Database: bhnnqi71g2wqrpwustfv"
echo "User: uqrllnmuff3ztkgj"
echo ""

echo "✅ Your application is ready for deployment!"
echo "🌐 After deployment, your API will be available at:"
echo "https://your-app-name.onrender.com/api/"
echo ""
echo "🔗 API Endpoints:"
echo "- POST /api/login - User login"
echo "- POST /api/signup - User registration"
echo "- POST /api/create-chat - Create new chat"
echo "- POST /api/send-message - Send message"
echo "- WebSocket: wss://your-app-name.onrender.com/socket"
